"""order item product snapshot fields

Revision ID: 1f5816d8f8f2
Revises: 9c5c5d203451
Create Date: 2026-05-31 14:00:07.070014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5816d8f8f2'
down_revision: Union[str, Sequence[str], None] = '9c5c5d203451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_slug', sa.String(length=280), nullable=True))
    op.add_column('order_items', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'image_url')
    op.drop_column('order_items', 'product_slug')
    # ### end Alembic commands ###
